---
- hosts: jenkins-slave
  become: true
  tasks: 
  - name: Update ubuntu repo and cache
    apt: 
      update_cache: yes
      force_apt_get: yes
      cache_valid_time: 3600

  - name: Install Java
    apt: 
      name: openjdk-11-jre
      state: present

  - name: download the maven package
    get_url:
      url: https://dlcdn.apache.org/maven/maven-3/3.9.4/binaries/apache-maven-3.9.4-bin.tar.gz
      dest: /opt

  - name: unarchive the zip file
    unarchive:
    src: /opt/apache-maven-3.9.4-bin.tar.gz
    dest: /opt
    remote_src: yes
  
  - name: Install docker
    apt: 
      name: docker.io
      state: present

  - name: give permission for the docker.sock to avoid service start
    file: 
      path: /var/run/docker.sock
      state: file
      mode: 0777

  - name: start docker service
    service: 
      name: docker
      state: started

  - name: enable the docker services
    service:
      name: docker
      enabled: yes